development:
  memory_cgroup_path: /home/hell/projects/temp/memory
  memory_stat: memory.stat
  docker_folder: docker
production:
  memory_cgroup_path: /sys/fs/cgroup/memory
  memory_stat: memory.stat
  docker_folder: docker